# Generated by Django 3.0.8 on 2020-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
        ),
    ]
