# Generated by Django 3.0.8 on 2020-09-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
